-- CREATE uuid-ossp EXTENSION
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- CREATE TABLE
CREATE TABLE NLP (
	ID UUID NOT NULL DEFAULT UUID_GENERATE_V1 (),
	OUTPUT_TEXT TEXT NOT NULL,
	INPUT_TEXT TEXT NOT NULL
);

--SELECT OUTPUT_TEXT,INPUT_TEXT FROM NLP
SELECT
	OUTPUT_TEXT,
	INPUT_TEXT
FROM
	NLP
FETCH FIRST
	5 ROWS ONLY;